[tool.black]
line-length = 88
target-version = ['py313']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | \.env
  | env
  | venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''